### ISSUE TITLE
Inferring Regulator that is an Event needs ReleaseDate as arg

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/Release#20]
Inferring Regulator that is an Event needs ReleaseDate as arg

See here: https://github.com/reactome/Release/blob/a9f802ed51653eacb999c81cfef52463bfae8f5b/scripts/release/orthoinference/infer_events.pl#L1010

**Comment by jweiser** [comment]
Committed in orthoinference_pathway_release_date branch
