### ISSUE TITLE
Better wording in warning message

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/Release#23]
Wording of message generated here:

https://github.com/reactome/Release/blob/master/scripts/release/generate_stable_ids_orthoinference/old_stable_id_mapping.pl#L68

...could be better. Maybe include the class of the instance, or something else to make the message look a little less serious (it's not a show-stopper, just a little odd).

One idea: don't even bother writing a message if the instance is some sort of Regulation (Regulations will never have direct species attribute so they will _always_ generate this message but that just clutters the log file).

**Comment by jweiser** [comment]
Warning message reworded
