### ISSUE TITLE
Suppress Log4Perl message

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/Release#24]
Log4Perl keeps printing this message:
```
Wide character in print at /usr/local/share/perl/5.20.2/Log/Log4perl/Appender/File.pm line 312.
```
Need to suppress this or fix the problem. It takes up a lot of logfile space and doesn't really say anything useful.

**Comment by jweiser** [comment]
Log4Perl configuration uses UTF8 to remove this warning
