### ISSUE TITLE
Add "go" ,"goa_slim"

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/Release#29]
It seems ENSEMBLMart has changed the response from this:

http://www.ensembl.org/biomart/martservice?type=listAttributes&mart=ENSEMBL_MART_ENSEMBL&virtualSchema=default&dataset=hsapiens_gene_ensembl&interface=default&attributePage=feature_page&attributeGroup=external&attributeCollection=xrefs

such that it no longer contains GO as an xref.

So... add "go" and "goa_slim" here:

https://github.com/reactome/Release/blob/master/modules/GKB/EnsEMBLMartUtils.pm#L164

**Comment by jweiser** [comment]
Have been added
